export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
export const REACT_APP_IMAGE_APP_TOKEN = process.env.REACT_APP_IMAGE_APP_TOKEN
export const REACT_APP_IMAGE_APP_KEY = process.env.REACT_APP_IMAGE_APP_KEY
export const REACT_APP_HAVANA_IMAGE_URL = process.env.REACT_APP_HAVANA_IMAGE_URL
export const REACT_APP_BOT_DETECTION_URL = process.env.REACT_APP_BOT_DETECTION_URL